# Generated by Django 3.2.9 on 2021-11-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='question',
        ),
    ]
