# Generated by Django 3.2.9 on 2021-11-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
