# Generated by Django 3.2.9 on 2021-11-25 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 16, 44, 33, 696887, tzinfo=utc)),
        ),
    ]
