# Generated by Django 3.2.9 on 2021-11-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_comment_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='limit',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
