# Generated by Django 3.2.9 on 2021-11-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_choice_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='limit',
        ),
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Published/Closed'),
        ),
    ]
