# Generated by Django 3.2.9 on 2021-11-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20211127_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
