# Generated by Django 3.2.9 on 2021-11-27 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_choice_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 23, 28, 9, 438870)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
