# Generated by Django 3.2.9 on 2021-11-27 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20211127_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 23, 30, 25, 896338)),
        ),
    ]
