# Generated by Django 3.2.9 on 2021-11-27 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_question_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 23, 32, 35, 246175)),
        ),
    ]
